
var a;a||(a=typeof Module !== 'undefined' ? Module : {});var b={},r;for(r in a)a.hasOwnProperty(r)&&(b[r]=a[r]);var t=!1,u=!1,aa=!1,ca=!1;t="object"===typeof window;u="function"===typeof importScripts;aa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ca=!t&&!aa&&!u;
if(a.ENVIRONMENT)throw Error("Module.ENVIRONMENT has been deprecated. To force the environment, use the ENVIRONMENT compile-time option (for example, -s ENVIRONMENT=web or -s ENVIRONMENT=node)");var v="",w,x,da,ea;
if(aa)v=u?require("path").dirname(v)+"/":__dirname+"/",w=function(c,d){da||(da=require("fs"));ea||(ea=require("path"));c=ea.normalize(c);return da.readFileSync(c,d?null:"utf8")},x=function(c){c=w(c,!0);c.buffer||(c=new Uint8Array(c));assert(c.buffer);return c},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),"undefined"!==typeof module&&(module.exports=a),process.on("uncaughtException",function(c){throw c;}),process.on("unhandledRejection",y),a.inspect=function(){return"[Emscripten Module object]"};
else if(ca)"undefined"!=typeof read&&(w=function(c){return read(c)}),x=function(c){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(c));c=read(c,"binary");assert("object"===typeof c);return c},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(t||u)u?v=self.location.href:document.currentScript&&(v=document.currentScript.src),v=0!==v.indexOf("blob:")?v.substr(0,
v.lastIndexOf("/")+1):"",w=function(c){var d=new XMLHttpRequest;d.open("GET",c,!1);d.send(null);return d.responseText},u&&(x=function(c){var d=new XMLHttpRequest;d.open("GET",c,!1);d.responseType="arraybuffer";d.send(null);return new Uint8Array(d.response)});else throw Error("environment detection error");a.print||console.log.bind(console);var z=a.printErr||console.warn.bind(console);for(r in b)b.hasOwnProperty(r)&&(a[r]=b[r]);b=null;
Object.getOwnPropertyDescriptor(a,"arguments")||Object.defineProperty(a,"arguments",{configurable:!0,get:function(){y("Module.arguments has been replaced with plain arguments_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});Object.getOwnPropertyDescriptor(a,"thisProgram")||Object.defineProperty(a,"thisProgram",{configurable:!0,get:function(){y("Module.thisProgram has been replaced with plain thisProgram (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
Object.getOwnPropertyDescriptor(a,"quit")||Object.defineProperty(a,"quit",{configurable:!0,get:function(){y("Module.quit has been replaced with plain quit_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});assert("undefined"===typeof a.memoryInitializerPrefixURL,"Module.memoryInitializerPrefixURL option was removed, use Module.locateFile instead");assert("undefined"===typeof a.pthreadMainPrefixURL,"Module.pthreadMainPrefixURL option was removed, use Module.locateFile instead");
assert("undefined"===typeof a.cdInitializerPrefixURL,"Module.cdInitializerPrefixURL option was removed, use Module.locateFile instead");assert("undefined"===typeof a.filePackagePrefixURL,"Module.filePackagePrefixURL option was removed, use Module.locateFile instead");assert("undefined"===typeof a.read,"Module.read option was removed (modify read_ in JS)");assert("undefined"===typeof a.readAsync,"Module.readAsync option was removed (modify readAsync in JS)");
assert("undefined"===typeof a.readBinary,"Module.readBinary option was removed (modify readBinary in JS)");assert("undefined"===typeof a.setWindowTitle,"Module.setWindowTitle option was removed (modify setWindowTitle in JS)");assert("undefined"===typeof a.TOTAL_MEMORY,"Module.TOTAL_MEMORY has been renamed Module.INITIAL_MEMORY");Object.getOwnPropertyDescriptor(a,"read")||Object.defineProperty(a,"read",{configurable:!0,get:function(){y("Module.read has been replaced with plain read_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
Object.getOwnPropertyDescriptor(a,"readAsync")||Object.defineProperty(a,"readAsync",{configurable:!0,get:function(){y("Module.readAsync has been replaced with plain readAsync (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});Object.getOwnPropertyDescriptor(a,"readBinary")||Object.defineProperty(a,"readBinary",{configurable:!0,get:function(){y("Module.readBinary has been replaced with plain readBinary (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
Object.getOwnPropertyDescriptor(a,"setWindowTitle")||Object.defineProperty(a,"setWindowTitle",{configurable:!0,get:function(){y("Module.setWindowTitle has been replaced with plain setWindowTitle (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});function fa(c){A||(A={});A[c]||(A[c]=1,z(c))}var A,B;a.wasmBinary&&(B=a.wasmBinary);
Object.getOwnPropertyDescriptor(a,"wasmBinary")||Object.defineProperty(a,"wasmBinary",{configurable:!0,get:function(){y("Module.wasmBinary has been replaced with plain wasmBinary (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});var noExitRuntime;a.noExitRuntime&&(noExitRuntime=a.noExitRuntime);Object.getOwnPropertyDescriptor(a,"noExitRuntime")||Object.defineProperty(a,"noExitRuntime",{configurable:!0,get:function(){y("Module.noExitRuntime has been replaced with plain noExitRuntime (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
"object"!==typeof WebAssembly&&y("no native wasm support detected");var C,ha=new WebAssembly.Table({initial:26,maximum:26,element:"anyfunc"}),ia=!1;function assert(c,d){c||y("Assertion failed: "+d)}function ja(c){var d=a["_"+c];assert(d,"Cannot call unknown function "+c+", make sure it is exported");return d}
function ka(c,d,e,f){var g={string:function(l){var n=0;if(null!==l&&void 0!==l&&0!==l){var q=(l.length<<2)+1;n=la(q);ma(l,n,q)}return n},array:function(l){var n=la(l.length);assert(0<=l.length,"writeArrayToMemory array must have a length (should be an array or typed array)");D.set(l,n);return n}},h=ja(c),k=[];c=0;assert("array"!==d,'Return type should not be "array".');if(f)for(var m=0;m<f.length;m++){var p=g[e[m]];p?(0===c&&(c=na()),k[m]=p(f[m])):k[m]=f[m]}e=h.apply(null,k);e=function(l){return"string"===
d?l?oa(l,void 0):"":"boolean"===d?!!l:l}(e);0!==c&&pa(c);return e}var qa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function oa(c,d){var e=E,f=c+d;for(d=c;e[d]&&!(d>=f);)++d;if(16<d-c&&e.subarray&&qa)return qa.decode(e.subarray(c,d));for(f="";c<d;){var g=e[c++];if(g&128){var h=e[c++]&63;if(192==(g&224))f+=String.fromCharCode((g&31)<<6|h);else{var k=e[c++]&63;224==(g&240)?g=(g&15)<<12|h<<6|k:(240!=(g&248)&&fa("Invalid UTF-8 leading byte 0x"+g.toString(16)+" encountered when deserializing a UTF-8 string on the asm.js/wasm heap to a JS string!"),g=(g&7)<<18|h<<12|k<<6|e[c++]&63);65536>g?f+=String.fromCharCode(g):
(g-=65536,f+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else f+=String.fromCharCode(g)}return f}
function ma(c,d,e){assert("number"==typeof e,"stringToUTF8(str, outPtr, maxBytesToWrite) is missing the third parameter that specifies the length of the output buffer!");var f=E;if(0<e){e=d+e-1;for(var g=0;g<c.length;++g){var h=c.charCodeAt(g);if(55296<=h&&57343>=h){var k=c.charCodeAt(++g);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(d>=e)break;f[d++]=h}else{if(2047>=h){if(d+1>=e)break;f[d++]=192|h>>6}else{if(65535>=h){if(d+2>=e)break;f[d++]=224|h>>12}else{if(d+3>=e)break;2097152<=h&&fa("Invalid Unicode code point 0x"+
h.toString(16)+" encountered when serializing a JS string to an UTF-8 string on the asm.js/wasm heap! (Valid unicode code points should be in range 0-0x1FFFFF).");f[d++]=240|h>>18;f[d++]=128|h>>12&63}f[d++]=128|h>>6&63}f[d++]=128|h&63}}f[d]=0}}var sa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function ta(c,d){assert(0==c%2,"Pointer passed to UTF16ToString must be aligned to two bytes!");var e=c>>1;for(var f=e+d/2;!(e>=f)&&F[e];)++e;e<<=1;if(32<e-c&&sa)return sa.decode(E.subarray(c,e));e=0;for(f="";;){var g=G[c+2*e>>1];if(0==g||e==d/2)return f;++e;f+=String.fromCharCode(g)}}
function ua(c,d,e){assert(0==d%2,"Pointer passed to stringToUTF16 must be aligned to two bytes!");assert("number"==typeof e,"stringToUTF16(str, outPtr, maxBytesToWrite) is missing the third parameter that specifies the length of the output buffer!");void 0===e&&(e=2147483647);if(2>e)return 0;e-=2;var f=d;e=e<2*c.length?e/2:c.length;for(var g=0;g<e;++g)G[d>>1]=c.charCodeAt(g),d+=2;G[d>>1]=0;return d-f}function va(c){return 2*c.length}
function wa(c,d){assert(0==c%4,"Pointer passed to UTF32ToString must be aligned to four bytes!");for(var e=0,f="";!(e>=d/4);){var g=H[c+4*e>>2];if(0==g)break;++e;65536<=g?(g-=65536,f+=String.fromCharCode(55296|g>>10,56320|g&1023)):f+=String.fromCharCode(g)}return f}
function xa(c,d,e){assert(0==d%4,"Pointer passed to stringToUTF32 must be aligned to four bytes!");assert("number"==typeof e,"stringToUTF32(str, outPtr, maxBytesToWrite) is missing the third parameter that specifies the length of the output buffer!");void 0===e&&(e=2147483647);if(4>e)return 0;var f=d;e=f+e-4;for(var g=0;g<c.length;++g){var h=c.charCodeAt(g);if(55296<=h&&57343>=h){var k=c.charCodeAt(++g);h=65536+((h&1023)<<10)|k&1023}H[d>>2]=h;d+=4;if(d+4>e)break}H[d>>2]=0;return d-f}
function ya(c){for(var d=0,e=0;e<c.length;++e){var f=c.charCodeAt(e);55296<=f&&57343>=f&&++e;d+=4}return d}var I,D,E,G,F,H,J,za,Aa;assert(!0,"stack must start aligned");assert(!0,"heap must start aligned");a.TOTAL_STACK&&assert(5242880===a.TOTAL_STACK,"the stack size can no longer be determined at runtime");var L=a.INITIAL_MEMORY||16777216;Object.getOwnPropertyDescriptor(a,"INITIAL_MEMORY")||Object.defineProperty(a,"INITIAL_MEMORY",{configurable:!0,get:function(){y("Module.INITIAL_MEMORY has been replaced with plain INITIAL_INITIAL_MEMORY (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
assert(5242880<=L,"INITIAL_MEMORY should be larger than TOTAL_STACK, was "+L+"! (TOTAL_STACK=5242880)");assert("undefined"!==typeof Int32Array&&"undefined"!==typeof Float64Array&&void 0!==Int32Array.prototype.subarray&&void 0!==Int32Array.prototype.set,"JS engine does not provide full typed array support");a.wasmMemory?C=a.wasmMemory:C=new WebAssembly.Memory({initial:L/65536,maximum:L/65536});C&&(I=C.buffer);L=I.byteLength;assert(0===L%65536);var M=I;I=M;a.HEAP8=D=new Int8Array(M);a.HEAP16=G=new Int16Array(M);
a.HEAP32=H=new Int32Array(M);a.HEAPU8=E=new Uint8Array(M);a.HEAPU16=F=new Uint16Array(M);a.HEAPU32=J=new Uint32Array(M);a.HEAPF32=za=new Float32Array(M);a.HEAPF64=Aa=new Float64Array(M);H[1288]=5248048;function Ba(){assert(!0);J[1293]=34821223;J[1294]=2310721022;H[0]=1668509029}
function N(){var c=J[1293],d=J[1294];34821223==c&&2310721022==d||y("Stack overflow! Stack cookie has been overwritten, expected hex dwords 0x89BACDFE and 0x2135467, but received 0x"+d.toString(16)+" "+c.toString(16));1668509029!==H[0]&&y("Runtime error: The application has corrupted its heap memory area (address zero)!")}var Ca=new Int16Array(1),Da=new Int8Array(Ca.buffer);Ca[0]=25459;if(115!==Da[0]||99!==Da[1])throw"Runtime error: expected the system to be little-endian!";
var Ea=[],Fa=[],Ga=[],Ha=[],Ia=!1;function Ja(){var c=a.preRun.shift();Ea.unshift(c)}assert(Math.imul,"This browser does not support Math.imul(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.fround,"This browser does not support Math.fround(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.clz32,"This browser does not support Math.clz32(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");
assert(Math.trunc,"This browser does not support Math.trunc(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");var O=0,P=null,Q=null,R={};
function Ka(){O++;a.monitorRunDependencies&&a.monitorRunDependencies(O);assert(!R["wasm-instantiate"]);R["wasm-instantiate"]=1;null===P&&"undefined"!==typeof setInterval&&(P=setInterval(function(){if(ia)clearInterval(P),P=null;else{var c=!1,d;for(d in R)c||(c=!0,z("still waiting on run dependencies:")),z("dependency: "+d);c&&z("(end of list)")}},1E4))}a.preloadedImages={};a.preloadedAudios={};
function y(c){if(a.onAbort)a.onAbort(c);z(c);ia=!0;c="abort("+c+") at ";a:{var d=Error();if(!d.stack){try{throw Error();}catch(e){d=e}if(!d.stack){d="(no stack trace available)";break a}}d=d.stack.toString()}a.extraStackTrace&&(d+="\n"+a.extraStackTrace());d=La(d);throw new WebAssembly.RuntimeError(c+d);}
function Ma(){y("Filesystem support (FS) was not included. The problem is that you are using files from JS, but files were not used from C/C++, so filesystem support was not auto-included. You can force-include filesystem support with  -s FORCE_FILESYSTEM=1")}a.FS_createDataFile=function(){Ma()};a.FS_createPreloadedFile=function(){Ma()};function Na(c){var d=S;return String.prototype.startsWith?d.startsWith(c):0===d.indexOf(c)}function Oa(){return Na("data:application/octet-stream;base64,")}
function T(c){return function(){var d=a.asm;assert(Ia,"native function `"+c+"` called before runtime initialization");assert(!0,"native function `"+c+"` called after runtime exit (use NO_EXIT_RUNTIME to keep it alive after main() exits)");d[c]||assert(d[c],"exported native function `"+c+"` not found");return d[c].apply(null,arguments)}}var S="fastled.wasm";if(!Oa()){var Pa=S;S=a.locateFile?a.locateFile(Pa,v):v+Pa}
function Qa(){try{if(B)return new Uint8Array(B);if(x)return x(S);throw"both async and sync fetching of the wasm failed";}catch(c){y(c)}}function Ra(){return B||!t&&!u||"function"!==typeof fetch||Na("file://")?Promise.resolve().then(Qa):fetch(S,{credentials:"same-origin"}).then(function(c){if(!c.ok)throw"failed to load wasm binary file at '"+S+"'";return c.arrayBuffer()}).catch(function(){return Qa()})}Fa.push({c:function(){Sa()}});
function U(c){for(;0<c.length;){var d=c.shift();if("function"==typeof d)d(a);else{var e=d.c;"number"===typeof e?void 0===d.b?ha.get(e)():ha.get(e)(d.b):e(void 0===d.b?null:d.b)}}}function La(c){return c.replace(/\b_Z[\w\d_]+/g,function(d){fa("warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling");return d===d?d:d+" ["+d+"]"})}function Ta(c){switch(c){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+c);}}
var Ua=void 0;function V(c){for(var d="";E[c];)d+=Ua[E[c++]];return d}var Va={},Wa={},Xa={};function Ya(c,d){if(void 0===c)c="_unknown";else{c=c.replace(/[^a-zA-Z0-9_]/g,"$");var e=c.charCodeAt(0);c=48<=e&&57>=e?"_"+c:c}return(new Function("body","return function "+c+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(d)}
function Za(c){var d=Error,e=Ya(c,function(f){this.name=c;this.message=f;f=Error(f).stack;void 0!==f&&(this.stack=this.toString()+"\n"+f.replace(/^Error(:[^\n]*)?\n/,""))});e.prototype=Object.create(d.prototype);e.prototype.constructor=e;e.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return e}var $a=void 0;function W(c){throw new $a(c);}
function X(c,d,e){e=e||{};if(!("argPackAdvance"in d))throw new TypeError("registerType registeredInstance requires argPackAdvance");var f=d.name;c||W('type "'+f+'" must have a positive integer typeid pointer');if(Wa.hasOwnProperty(c)){if(e.f)return;W("Cannot register type '"+f+"' twice")}Wa[c]=d;delete Xa[c];Va.hasOwnProperty(c)&&(d=Va[c],delete Va[c],d.forEach(function(g){g()}))}var ab=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function bb(c){switch(c){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var d=ab.length?ab.pop():Y.length;Y[d]={g:1,value:c};return d}}function cb(c){return this.fromWireType(J[c>>2])}function db(c){if(null===c)return"null";var d=typeof c;return"object"===d||"array"===d||"function"===d?c.toString():""+c}
function eb(c,d){switch(d){case 2:return function(e){return this.fromWireType(za[e>>2])};case 3:return function(e){return this.fromWireType(Aa[e>>3])};default:throw new TypeError("Unknown float type: "+c);}}
function fb(c,d,e){switch(d){case 0:return e?function(f){return D[f]}:function(f){return E[f]};case 1:return e?function(f){return G[f>>1]}:function(f){return F[f>>1]};case 2:return e?function(f){return H[f>>2]}:function(f){return J[f>>2]};default:throw new TypeError("Unknown integer type: "+c);}}for(var gb=Array(256),hb=0;256>hb;++hb)gb[hb]=String.fromCharCode(hb);Ua=gb;$a=a.BindingError=Za("BindingError");a.InternalError=Za("InternalError");
a.count_emval_handles=function(){for(var c=0,d=5;d<Y.length;++d)void 0!==Y[d]&&++c;return c};a.get_first_emval=function(){for(var c=5;c<Y.length;++c)if(void 0!==Y[c])return Y[c];return null};
var jb={_embind_register_bool:function(c,d,e,f,g){var h=Ta(e);d=V(d);X(c,{name:d,fromWireType:function(k){return!!k},toWireType:function(k,m){return m?f:g},argPackAdvance:8,readValueFromPointer:function(k){if(1===e)var m=D;else if(2===e)m=G;else if(4===e)m=H;else throw new TypeError("Unknown boolean type size: "+d);return this.fromWireType(m[k>>h])},a:null})},_embind_register_emval:function(c,d){d=V(d);X(c,{name:d,fromWireType:function(e){var f=Y[e].value;4<e&&0===--Y[e].g&&(Y[e]=void 0,ab.push(e));
return f},toWireType:function(e,f){return bb(f)},argPackAdvance:8,readValueFromPointer:cb,a:null})},_embind_register_float:function(c,d,e){e=Ta(e);d=V(d);X(c,{name:d,fromWireType:function(f){return f},toWireType:function(f,g){if("number"!==typeof g&&"boolean"!==typeof g)throw new TypeError('Cannot convert "'+db(g)+'" to '+this.name);return g},argPackAdvance:8,readValueFromPointer:eb(d,e),a:null})},_embind_register_integer:function(c,d,e,f,g){function h(l){return l}d=V(d);-1===g&&(g=4294967295);var k=
Ta(e);if(0===f){var m=32-8*e;h=function(l){return l<<m>>>m}}var p=-1!=d.indexOf("unsigned");X(c,{name:d,fromWireType:h,toWireType:function(l,n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+db(n)+'" to '+this.name);if(n<f||n>g)throw new TypeError('Passing a number "'+db(n)+'" from JS side to C/C++ side to an argument of type "'+d+'", which is outside the valid range ['+f+", "+g+"]!");return p?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:fb(d,k,0!==f),a:null})},
_embind_register_memory_view:function(c,d,e){function f(h){h>>=2;return new g(I,J[h+1],J[h])}var g=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][d];e=V(e);X(c,{name:e,fromWireType:f,argPackAdvance:8,readValueFromPointer:f},{f:!0})},_embind_register_std_string:function(c,d){d=V(d);var e="std::string"===d;X(c,{name:d,fromWireType:function(f){var g=J[f>>2];if(e)for(var h=f+4,k=0;k<=g;++k){var m=f+4+k;if(k==g||0==E[m]){h=h?oa(h,m-h):"";if(void 0===p)var p=
h;else p+=String.fromCharCode(0),p+=h;h=m+1}}else{p=Array(g);for(k=0;k<g;++k)p[k]=String.fromCharCode(E[f+4+k]);p=p.join("")}Z(f);return p},toWireType:function(f,g){g instanceof ArrayBuffer&&(g=new Uint8Array(g));var h="string"===typeof g;h||g instanceof Uint8Array||g instanceof Uint8ClampedArray||g instanceof Int8Array||W("Cannot pass non-string to std::string");var k=(e&&h?function(){for(var l=0,n=0;n<g.length;++n){var q=g.charCodeAt(n);55296<=q&&57343>=q&&(q=65536+((q&1023)<<10)|g.charCodeAt(++n)&
1023);127>=q?++l:l=2047>=q?l+2:65535>=q?l+3:l+4}return l}:function(){return g.length})(),m=ib(4+k+1);J[m>>2]=k;if(e&&h)ma(g,m+4,k+1);else if(h)for(h=0;h<k;++h){var p=g.charCodeAt(h);255<p&&(Z(m),W("String has UTF-16 code units that do not fit in 8 bits"));E[m+4+h]=p}else for(h=0;h<k;++h)E[m+4+h]=g[h];null!==f&&f.push(Z,m);return m},argPackAdvance:8,readValueFromPointer:cb,a:function(f){Z(f)}})},_embind_register_std_wstring:function(c,d,e){e=V(e);if(2===d){var f=ta;var g=ua;var h=va;var k=function(){return F};
var m=1}else 4===d&&(f=wa,g=xa,h=ya,k=function(){return J},m=2);X(c,{name:e,fromWireType:function(p){for(var l=J[p>>2],n=k(),q,K=p+4,ba=0;ba<=l;++ba){var ra=p+4+ba*d;if(ba==l||0==n[ra>>m])K=f(K,ra-K),void 0===q?q=K:(q+=String.fromCharCode(0),q+=K),K=ra+d}Z(p);return q},toWireType:function(p,l){"string"!==typeof l&&W("Cannot pass non-string to C++ string type "+e);var n=h(l),q=ib(4+n+d);J[q>>2]=n>>m;g(l,q+4,n+d);null!==p&&p.push(Z,q);return q},argPackAdvance:8,readValueFromPointer:cb,a:function(p){Z(p)}})},
_embind_register_void:function(c,d){d=V(d);X(c,{h:!0,name:d,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},abort:function(){y()},emscripten_get_sbrk_ptr:function(){return 5152},emscripten_memcpy_big:function(c,d,e){E.copyWithin(c,d,d+e)},emscripten_resize_heap:function(c){y("Cannot enlarge memory arrays to size "+(c>>>0)+" bytes (OOM). Either (1) compile with  -s INITIAL_MEMORY=X  with X higher than the current value "+D.length+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},
gettimeofday:function(c){var d=Date.now();H[c>>2]=d/1E3|0;H[c+4>>2]=d%1E3*1E3|0;return 0},memory:C,table:ha};
(function(){function c(h){a.asm=h.exports;O--;a.monitorRunDependencies&&a.monitorRunDependencies(O);assert(R["wasm-instantiate"]);delete R["wasm-instantiate"];0==O&&(null!==P&&(clearInterval(P),P=null),Q&&(h=Q,Q=null,h()))}function d(h){assert(a===g,"the Module object should not be replaced during async compilation - perhaps the order of HTML elements is wrong?");g=null;c(h.instance)}function e(h){return Ra().then(function(k){return WebAssembly.instantiate(k,f)}).then(h,function(k){z("failed to asynchronously prepare wasm: "+
k);y(k)})}var f={env:jb,wasi_snapshot_preview1:jb};Ka();var g=a;if(a.instantiateWasm)try{return a.instantiateWasm(f,c)}catch(h){return z("Module.instantiateWasm callback failed with error: "+h),!1}(function(){if(B||"function"!==typeof WebAssembly.instantiateStreaming||Oa()||Na("file://")||"function"!==typeof fetch)return e(d);fetch(S,{credentials:"same-origin"}).then(function(h){return WebAssembly.instantiateStreaming(h,f).then(d,function(k){z("wasm streaming compile failed: "+k);z("falling back to ArrayBuffer instantiation");
return e(d)})})})();return{}})();var Sa=a.___wasm_call_ctors=T("__wasm_call_ctors");a._demo_reel100=T("demo_reel100");a._demo_pride=T("demo_pride");a._demo_twinklefox=T("demo_twinklefox");a._demo_fire2012=T("demo_fire2012");a._demo_pacifica=T("demo_pacifica");a.___getTypeName=T("__getTypeName");a.___embind_register_native_and_builtin_types=T("__embind_register_native_and_builtin_types");a.___errno_location=T("__errno_location");var ib=a._malloc=T("malloc");a._fflush=T("fflush");
var na=a.stackSave=T("stackSave"),pa=a.stackRestore=T("stackRestore"),la=a.stackAlloc=T("stackAlloc"),Z=a._free=T("free");a.__growWasmMemory=T("__growWasmMemory");Object.getOwnPropertyDescriptor(a,"intArrayFromString")||(a.intArrayFromString=function(){y("'intArrayFromString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"intArrayToString")||(a.intArrayToString=function(){y("'intArrayToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
a.ccall=ka;a.cwrap=function(c,d,e,f){return function(){return ka(c,d,e,arguments,f)}};Object.getOwnPropertyDescriptor(a,"setValue")||(a.setValue=function(){y("'setValue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getValue")||(a.getValue=function(){y("'getValue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"allocate")||(a.allocate=function(){y("'allocate' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getMemory")||(a.getMemory=function(){y("'getMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"UTF8ArrayToString")||(a.UTF8ArrayToString=function(){y("'UTF8ArrayToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"UTF8ToString")||(a.UTF8ToString=function(){y("'UTF8ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToUTF8Array")||(a.stringToUTF8Array=function(){y("'stringToUTF8Array' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToUTF8")||(a.stringToUTF8=function(){y("'stringToUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"lengthBytesUTF8")||(a.lengthBytesUTF8=function(){y("'lengthBytesUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stackTrace")||(a.stackTrace=function(){y("'stackTrace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addOnPreRun")||(a.addOnPreRun=function(){y("'addOnPreRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"addOnInit")||(a.addOnInit=function(){y("'addOnInit' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addOnPreMain")||(a.addOnPreMain=function(){y("'addOnPreMain' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addOnExit")||(a.addOnExit=function(){y("'addOnExit' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"addOnPostRun")||(a.addOnPostRun=function(){y("'addOnPostRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeStringToMemory")||(a.writeStringToMemory=function(){y("'writeStringToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeArrayToMemory")||(a.writeArrayToMemory=function(){y("'writeArrayToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"writeAsciiToMemory")||(a.writeAsciiToMemory=function(){y("'writeAsciiToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addRunDependency")||(a.addRunDependency=function(){y("'addRunDependency' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"removeRunDependency")||(a.removeRunDependency=function(){y("'removeRunDependency' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"FS_createFolder")||(a.FS_createFolder=function(){y("'FS_createFolder' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"FS_createPath")||(a.FS_createPath=function(){y("'FS_createPath' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"FS_createDataFile")||(a.FS_createDataFile=function(){y("'FS_createDataFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"FS_createPreloadedFile")||(a.FS_createPreloadedFile=function(){y("'FS_createPreloadedFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"FS_createLazyFile")||(a.FS_createLazyFile=function(){y("'FS_createLazyFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"FS_createLink")||(a.FS_createLink=function(){y("'FS_createLink' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"FS_createDevice")||(a.FS_createDevice=function(){y("'FS_createDevice' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"FS_unlink")||(a.FS_unlink=function(){y("'FS_unlink' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"dynamicAlloc")||(a.dynamicAlloc=function(){y("'dynamicAlloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"loadDynamicLibrary")||(a.loadDynamicLibrary=function(){y("'loadDynamicLibrary' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"loadWebAssemblyModule")||(a.loadWebAssemblyModule=function(){y("'loadWebAssemblyModule' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getLEB")||(a.getLEB=function(){y("'getLEB' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getFunctionTables")||(a.getFunctionTables=function(){y("'getFunctionTables' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"alignFunctionTables")||(a.alignFunctionTables=function(){y("'alignFunctionTables' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registerFunctions")||(a.registerFunctions=function(){y("'registerFunctions' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"addFunction")||(a.addFunction=function(){y("'addFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"removeFunction")||(a.removeFunction=function(){y("'removeFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getFuncWrapper")||(a.getFuncWrapper=function(){y("'getFuncWrapper' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"prettyPrint")||(a.prettyPrint=function(){y("'prettyPrint' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"makeBigInt")||(a.makeBigInt=function(){y("'makeBigInt' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"dynCall")||(a.dynCall=function(){y("'dynCall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getCompilerSetting")||(a.getCompilerSetting=function(){y("'getCompilerSetting' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"print")||(a.print=function(){y("'print' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"printErr")||(a.printErr=function(){y("'printErr' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getTempRet0")||(a.getTempRet0=function(){y("'getTempRet0' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"setTempRet0")||(a.setTempRet0=function(){y("'setTempRet0' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"callMain")||(a.callMain=function(){y("'callMain' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"abort")||(a.abort=function(){y("'abort' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToNewUTF8")||(a.stringToNewUTF8=function(){y("'stringToNewUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"abortOnCannotGrowMemory")||(a.abortOnCannotGrowMemory=function(){y("'abortOnCannotGrowMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"emscripten_realloc_buffer")||(a.emscripten_realloc_buffer=function(){y("'emscripten_realloc_buffer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ENV")||(a.ENV=function(){y("'ENV' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ERRNO_CODES")||(a.ERRNO_CODES=function(){y("'ERRNO_CODES' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"ERRNO_MESSAGES")||(a.ERRNO_MESSAGES=function(){y("'ERRNO_MESSAGES' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"setErrNo")||(a.setErrNo=function(){y("'setErrNo' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"DNS")||(a.DNS=function(){y("'DNS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"GAI_ERRNO_MESSAGES")||(a.GAI_ERRNO_MESSAGES=function(){y("'GAI_ERRNO_MESSAGES' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"Protocols")||(a.Protocols=function(){y("'Protocols' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"Sockets")||(a.Sockets=function(){y("'Sockets' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"traverseStack")||(a.traverseStack=function(){y("'traverseStack' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"UNWIND_CACHE")||(a.UNWIND_CACHE=function(){y("'UNWIND_CACHE' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"withBuiltinMalloc")||(a.withBuiltinMalloc=function(){y("'withBuiltinMalloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"readAsmConstArgsArray")||(a.readAsmConstArgsArray=function(){y("'readAsmConstArgsArray' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"readAsmConstArgs")||(a.readAsmConstArgs=function(){y("'readAsmConstArgs' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"mainThreadEM_ASM")||(a.mainThreadEM_ASM=function(){y("'mainThreadEM_ASM' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"jstoi_q")||(a.jstoi_q=function(){y("'jstoi_q' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"jstoi_s")||(a.jstoi_s=function(){y("'jstoi_s' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getExecutableName")||(a.getExecutableName=function(){y("'getExecutableName' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"listenOnce")||(a.listenOnce=function(){y("'listenOnce' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"autoResumeAudioContext")||(a.autoResumeAudioContext=function(){y("'autoResumeAudioContext' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"dynCallLegacy")||(a.dynCallLegacy=function(){y("'dynCallLegacy' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getDynCaller")||(a.getDynCaller=function(){y("'getDynCaller' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"dynCall")||(a.dynCall=function(){y("'dynCall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"callRuntimeCallbacks")||(a.callRuntimeCallbacks=function(){y("'callRuntimeCallbacks' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"abortStackOverflow")||(a.abortStackOverflow=function(){y("'abortStackOverflow' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"reallyNegative")||(a.reallyNegative=function(){y("'reallyNegative' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"unSign")||(a.unSign=function(){y("'unSign' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"reSign")||(a.reSign=function(){y("'reSign' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"formatString")||(a.formatString=function(){y("'formatString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"PATH")||(a.PATH=function(){y("'PATH' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"PATH_FS")||(a.PATH_FS=function(){y("'PATH_FS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"SYSCALLS")||(a.SYSCALLS=function(){y("'SYSCALLS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"syscallMmap2")||(a.syscallMmap2=function(){y("'syscallMmap2' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"syscallMunmap")||(a.syscallMunmap=function(){y("'syscallMunmap' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"flush_NO_FILESYSTEM")||(a.flush_NO_FILESYSTEM=function(){y("'flush_NO_FILESYSTEM' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"JSEvents")||(a.JSEvents=function(){y("'JSEvents' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"specialHTMLTargets")||(a.specialHTMLTargets=function(){y("'specialHTMLTargets' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"maybeCStringToJsString")||(a.maybeCStringToJsString=function(){y("'maybeCStringToJsString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"findEventTarget")||(a.findEventTarget=function(){y("'findEventTarget' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"findCanvasEventTarget")||(a.findCanvasEventTarget=function(){y("'findCanvasEventTarget' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"polyfillSetImmediate")||(a.polyfillSetImmediate=function(){y("'polyfillSetImmediate' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"demangle")||(a.demangle=function(){y("'demangle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"demangleAll")||(a.demangleAll=function(){y("'demangleAll' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"jsStackTrace")||(a.jsStackTrace=function(){y("'jsStackTrace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stackTrace")||(a.stackTrace=function(){y("'stackTrace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getEnvStrings")||(a.getEnvStrings=function(){y("'getEnvStrings' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"checkWasiClock")||(a.checkWasiClock=function(){y("'checkWasiClock' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeI53ToI64")||(a.writeI53ToI64=function(){y("'writeI53ToI64' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"writeI53ToI64Clamped")||(a.writeI53ToI64Clamped=function(){y("'writeI53ToI64Clamped' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeI53ToI64Signaling")||(a.writeI53ToI64Signaling=function(){y("'writeI53ToI64Signaling' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeI53ToU64Clamped")||(a.writeI53ToU64Clamped=function(){y("'writeI53ToU64Clamped' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"writeI53ToU64Signaling")||(a.writeI53ToU64Signaling=function(){y("'writeI53ToU64Signaling' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"readI53FromI64")||(a.readI53FromI64=function(){y("'readI53FromI64' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"readI53FromU64")||(a.readI53FromU64=function(){y("'readI53FromU64' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"convertI32PairToI53")||(a.convertI32PairToI53=function(){y("'convertI32PairToI53' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"convertU32PairToI53")||(a.convertU32PairToI53=function(){y("'convertU32PairToI53' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"exceptionLast")||(a.exceptionLast=function(){y("'exceptionLast' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"exceptionCaught")||(a.exceptionCaught=function(){y("'exceptionCaught' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"exceptionThrowBuf")||(a.exceptionThrowBuf=function(){y("'exceptionThrowBuf' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ExceptionInfoAttrs")||(a.ExceptionInfoAttrs=function(){y("'ExceptionInfoAttrs' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"ExceptionInfo")||(a.ExceptionInfo=function(){y("'ExceptionInfo' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"CatchInfo")||(a.CatchInfo=function(){y("'CatchInfo' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"exception_addRef")||(a.exception_addRef=function(){y("'exception_addRef' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"exception_decRef")||(a.exception_decRef=function(){y("'exception_decRef' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"Browser")||(a.Browser=function(){y("'Browser' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"funcWrappers")||(a.funcWrappers=function(){y("'funcWrappers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getFuncWrapper")||(a.getFuncWrapper=function(){y("'getFuncWrapper' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"setMainLoop")||(a.setMainLoop=function(){y("'setMainLoop' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"FS")||(a.FS=function(){y("'FS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"MEMFS")||(a.MEMFS=function(){y("'MEMFS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"TTY")||(a.TTY=function(){y("'TTY' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"PIPEFS")||(a.PIPEFS=function(){y("'PIPEFS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"SOCKFS")||(a.SOCKFS=function(){y("'SOCKFS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"tempFixedLengthArray")||(a.tempFixedLengthArray=function(){y("'tempFixedLengthArray' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"miniTempWebGLFloatBuffers")||(a.miniTempWebGLFloatBuffers=function(){y("'miniTempWebGLFloatBuffers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"heapObjectForWebGLType")||(a.heapObjectForWebGLType=function(){y("'heapObjectForWebGLType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"heapAccessShiftForWebGLHeap")||(a.heapAccessShiftForWebGLHeap=function(){y("'heapAccessShiftForWebGLHeap' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GL")||(a.GL=function(){y("'GL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGet")||(a.emscriptenWebGLGet=function(){y("'emscriptenWebGLGet' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"computeUnpackAlignedImageSize")||(a.computeUnpackAlignedImageSize=function(){y("'computeUnpackAlignedImageSize' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGetTexPixelData")||(a.emscriptenWebGLGetTexPixelData=function(){y("'emscriptenWebGLGetTexPixelData' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGetUniform")||(a.emscriptenWebGLGetUniform=function(){y("'emscriptenWebGLGetUniform' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGetVertexAttrib")||(a.emscriptenWebGLGetVertexAttrib=function(){y("'emscriptenWebGLGetVertexAttrib' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeGLArray")||(a.writeGLArray=function(){y("'writeGLArray' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"AL")||(a.AL=function(){y("'AL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"SDL_unicode")||(a.SDL_unicode=function(){y("'SDL_unicode' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"SDL_ttfContext")||(a.SDL_ttfContext=function(){y("'SDL_ttfContext' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"SDL_audio")||(a.SDL_audio=function(){y("'SDL_audio' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"SDL")||(a.SDL=function(){y("'SDL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"SDL_gfx")||(a.SDL_gfx=function(){y("'SDL_gfx' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GLUT")||(a.GLUT=function(){y("'GLUT' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"EGL")||(a.EGL=function(){y("'EGL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GLFW_Window")||(a.GLFW_Window=function(){y("'GLFW_Window' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GLFW")||(a.GLFW=function(){y("'GLFW' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"GLEW")||(a.GLEW=function(){y("'GLEW' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"IDBStore")||(a.IDBStore=function(){y("'IDBStore' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"runAndAbortIfError")||(a.runAndAbortIfError=function(){y("'runAndAbortIfError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"emval_handle_array")||(a.emval_handle_array=function(){y("'emval_handle_array' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emval_free_list")||(a.emval_free_list=function(){y("'emval_free_list' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emval_symbols")||(a.emval_symbols=function(){y("'emval_symbols' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"init_emval")||(a.init_emval=function(){y("'init_emval' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"count_emval_handles")||(a.count_emval_handles=function(){y("'count_emval_handles' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"get_first_emval")||(a.get_first_emval=function(){y("'get_first_emval' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getStringOrSymbol")||(a.getStringOrSymbol=function(){y("'getStringOrSymbol' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"requireHandle")||(a.requireHandle=function(){y("'requireHandle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emval_newers")||(a.emval_newers=function(){y("'emval_newers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"craftEmvalAllocator")||(a.craftEmvalAllocator=function(){y("'craftEmvalAllocator' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emval_get_global")||(a.emval_get_global=function(){y("'emval_get_global' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emval_methodCallers")||(a.emval_methodCallers=function(){y("'emval_methodCallers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"InternalError")||(a.InternalError=function(){y("'InternalError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"BindingError")||(a.BindingError=function(){y("'BindingError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"UnboundTypeError")||(a.UnboundTypeError=function(){y("'UnboundTypeError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"PureVirtualError")||(a.PureVirtualError=function(){y("'PureVirtualError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"init_embind")||(a.init_embind=function(){y("'init_embind' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"throwInternalError")||(a.throwInternalError=function(){y("'throwInternalError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"throwBindingError")||(a.throwBindingError=function(){y("'throwBindingError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"throwUnboundTypeError")||(a.throwUnboundTypeError=function(){y("'throwUnboundTypeError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ensureOverloadTable")||(a.ensureOverloadTable=function(){y("'ensureOverloadTable' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"exposePublicSymbol")||(a.exposePublicSymbol=function(){y("'exposePublicSymbol' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"replacePublicSymbol")||(a.replacePublicSymbol=function(){y("'replacePublicSymbol' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"extendError")||(a.extendError=function(){y("'extendError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"createNamedFunction")||(a.createNamedFunction=function(){y("'createNamedFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registeredInstances")||(a.registeredInstances=function(){y("'registeredInstances' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getBasestPointer")||(a.getBasestPointer=function(){y("'getBasestPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"registerInheritedInstance")||(a.registerInheritedInstance=function(){y("'registerInheritedInstance' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"unregisterInheritedInstance")||(a.unregisterInheritedInstance=function(){y("'unregisterInheritedInstance' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getInheritedInstance")||(a.getInheritedInstance=function(){y("'getInheritedInstance' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getInheritedInstanceCount")||(a.getInheritedInstanceCount=function(){y("'getInheritedInstanceCount' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getLiveInheritedInstances")||(a.getLiveInheritedInstances=function(){y("'getLiveInheritedInstances' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registeredTypes")||(a.registeredTypes=function(){y("'registeredTypes' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"awaitingDependencies")||(a.awaitingDependencies=function(){y("'awaitingDependencies' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"typeDependencies")||(a.typeDependencies=function(){y("'typeDependencies' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registeredPointers")||(a.registeredPointers=function(){y("'registeredPointers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registerType")||(a.registerType=function(){y("'registerType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"whenDependentTypesAreResolved")||(a.whenDependentTypesAreResolved=function(){y("'whenDependentTypesAreResolved' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"embind_charCodes")||(a.embind_charCodes=function(){y("'embind_charCodes' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"embind_init_charCodes")||(a.embind_init_charCodes=function(){y("'embind_init_charCodes' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"readLatin1String")||(a.readLatin1String=function(){y("'readLatin1String' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getTypeName")||(a.getTypeName=function(){y("'getTypeName' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"heap32VectorToArray")||(a.heap32VectorToArray=function(){y("'heap32VectorToArray' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"requireRegisteredType")||(a.requireRegisteredType=function(){y("'requireRegisteredType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getShiftFromSize")||(a.getShiftFromSize=function(){y("'getShiftFromSize' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"integerReadValueFromPointer")||(a.integerReadValueFromPointer=function(){y("'integerReadValueFromPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"enumReadValueFromPointer")||(a.enumReadValueFromPointer=function(){y("'enumReadValueFromPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"floatReadValueFromPointer")||(a.floatReadValueFromPointer=function(){y("'floatReadValueFromPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"simpleReadValueFromPointer")||(a.simpleReadValueFromPointer=function(){y("'simpleReadValueFromPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"runDestructors")||(a.runDestructors=function(){y("'runDestructors' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"new_")||(a.new_=function(){y("'new_' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"craftInvokerFunction")||(a.craftInvokerFunction=function(){y("'craftInvokerFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"embind__requireFunction")||(a.embind__requireFunction=function(){y("'embind__requireFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"tupleRegistrations")||(a.tupleRegistrations=function(){y("'tupleRegistrations' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"structRegistrations")||(a.structRegistrations=function(){y("'structRegistrations' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"genericPointerToWireType")||(a.genericPointerToWireType=function(){y("'genericPointerToWireType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"constNoSmartPtrRawPointerToWireType")||(a.constNoSmartPtrRawPointerToWireType=function(){y("'constNoSmartPtrRawPointerToWireType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"nonConstNoSmartPtrRawPointerToWireType")||(a.nonConstNoSmartPtrRawPointerToWireType=function(){y("'nonConstNoSmartPtrRawPointerToWireType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"init_RegisteredPointer")||(a.init_RegisteredPointer=function(){y("'init_RegisteredPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"RegisteredPointer")||(a.RegisteredPointer=function(){y("'RegisteredPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"RegisteredPointer_getPointee")||(a.RegisteredPointer_getPointee=function(){y("'RegisteredPointer_getPointee' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"RegisteredPointer_destructor")||(a.RegisteredPointer_destructor=function(){y("'RegisteredPointer_destructor' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"RegisteredPointer_deleteObject")||(a.RegisteredPointer_deleteObject=function(){y("'RegisteredPointer_deleteObject' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"RegisteredPointer_fromWireType")||(a.RegisteredPointer_fromWireType=function(){y("'RegisteredPointer_fromWireType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"runDestructor")||(a.runDestructor=function(){y("'runDestructor' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"releaseClassHandle")||(a.releaseClassHandle=function(){y("'releaseClassHandle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"finalizationGroup")||(a.finalizationGroup=function(){y("'finalizationGroup' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"detachFinalizer_deps")||(a.detachFinalizer_deps=function(){y("'detachFinalizer_deps' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"detachFinalizer")||(a.detachFinalizer=function(){y("'detachFinalizer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"attachFinalizer")||(a.attachFinalizer=function(){y("'attachFinalizer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"makeClassHandle")||(a.makeClassHandle=function(){y("'makeClassHandle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"init_ClassHandle")||(a.init_ClassHandle=function(){y("'init_ClassHandle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"ClassHandle")||(a.ClassHandle=function(){y("'ClassHandle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ClassHandle_isAliasOf")||(a.ClassHandle_isAliasOf=function(){y("'ClassHandle_isAliasOf' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"throwInstanceAlreadyDeleted")||(a.throwInstanceAlreadyDeleted=function(){y("'throwInstanceAlreadyDeleted' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"ClassHandle_clone")||(a.ClassHandle_clone=function(){y("'ClassHandle_clone' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ClassHandle_delete")||(a.ClassHandle_delete=function(){y("'ClassHandle_delete' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"deletionQueue")||(a.deletionQueue=function(){y("'deletionQueue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"ClassHandle_isDeleted")||(a.ClassHandle_isDeleted=function(){y("'ClassHandle_isDeleted' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ClassHandle_deleteLater")||(a.ClassHandle_deleteLater=function(){y("'ClassHandle_deleteLater' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"flushPendingDeletes")||(a.flushPendingDeletes=function(){y("'flushPendingDeletes' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"delayFunction")||(a.delayFunction=function(){y("'delayFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"setDelayFunction")||(a.setDelayFunction=function(){y("'setDelayFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"RegisteredClass")||(a.RegisteredClass=function(){y("'RegisteredClass' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"shallowCopyInternalPointer")||(a.shallowCopyInternalPointer=function(){y("'shallowCopyInternalPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"downcastPointer")||(a.downcastPointer=function(){y("'downcastPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"upcastPointer")||(a.upcastPointer=function(){y("'upcastPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"validateThis")||(a.validateThis=function(){y("'validateThis' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"char_0")||(a.char_0=function(){y("'char_0' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"char_9")||(a.char_9=function(){y("'char_9' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"makeLegalFunctionName")||(a.makeLegalFunctionName=function(){y("'makeLegalFunctionName' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"warnOnce")||(a.warnOnce=function(){y("'warnOnce' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stackSave")||(a.stackSave=function(){y("'stackSave' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"stackRestore")||(a.stackRestore=function(){y("'stackRestore' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stackAlloc")||(a.stackAlloc=function(){y("'stackAlloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"AsciiToString")||(a.AsciiToString=function(){y("'AsciiToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"stringToAscii")||(a.stringToAscii=function(){y("'stringToAscii' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"UTF16ToString")||(a.UTF16ToString=function(){y("'UTF16ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToUTF16")||(a.stringToUTF16=function(){y("'stringToUTF16' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"lengthBytesUTF16")||(a.lengthBytesUTF16=function(){y("'lengthBytesUTF16' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"UTF32ToString")||(a.UTF32ToString=function(){y("'UTF32ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToUTF32")||(a.stringToUTF32=function(){y("'stringToUTF32' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"lengthBytesUTF32")||(a.lengthBytesUTF32=function(){y("'lengthBytesUTF32' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"allocateUTF8")||(a.allocateUTF8=function(){y("'allocateUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"allocateUTF8OnStack")||(a.allocateUTF8OnStack=function(){y("'allocateUTF8OnStack' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
a.writeStackCookie=Ba;a.checkStackCookie=N;Object.getOwnPropertyDescriptor(a,"ALLOC_NORMAL")||Object.defineProperty(a,"ALLOC_NORMAL",{configurable:!0,get:function(){y("'ALLOC_NORMAL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});Object.getOwnPropertyDescriptor(a,"ALLOC_STACK")||Object.defineProperty(a,"ALLOC_STACK",{configurable:!0,get:function(){y("'ALLOC_STACK' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});
Object.getOwnPropertyDescriptor(a,"ALLOC_DYNAMIC")||Object.defineProperty(a,"ALLOC_DYNAMIC",{configurable:!0,get:function(){y("'ALLOC_DYNAMIC' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});Object.getOwnPropertyDescriptor(a,"ALLOC_NONE")||Object.defineProperty(a,"ALLOC_NONE",{configurable:!0,get:function(){y("'ALLOC_NONE' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});var kb;Q=function lb(){kb||mb();kb||(Q=lb)};
function mb(){function c(){if(!kb&&(kb=!0,a.calledRun=!0,!ia)){N();assert(!Ia);Ia=!0;U(Fa);N();U(Ga);if(a.onRuntimeInitialized)a.onRuntimeInitialized();assert(!a._main,'compiled without a main, but one is present. if you added it from JS, use Module["onRuntimeInitialized"]');N();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var d=a.postRun.shift();Ha.unshift(d)}U(Ha)}}if(!(0<O)){Ba();if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)Ja();
U(Ea);0<O||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);c()},1)):c(),N())}}a.run=mb;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();noExitRuntime=!0;mb();
