
var a;a||(a=typeof Module !== 'undefined' ? Module : {});var b={},r;for(r in a)a.hasOwnProperty(r)&&(b[r]=a[r]);var t=!1,u=!1,v=!1,aa=!1;t="object"===typeof window;u="function"===typeof importScripts;v="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;aa=!t&&!v&&!u;
if(a.ENVIRONMENT)throw Error("Module.ENVIRONMENT has been deprecated. To force the environment, use the ENVIRONMENT compile-time option (for example, -s ENVIRONMENT=web or -s ENVIRONMENT=node)");var w="",x,y,ba,da;
if(v)w=u?require("path").dirname(w)+"/":__dirname+"/",x=function(c,d){ba||(ba=require("fs"));da||(da=require("path"));c=da.normalize(c);return ba.readFileSync(c,d?null:"utf8")},y=function(c){c=x(c,!0);c.buffer||(c=new Uint8Array(c));assert(c.buffer);return c},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),"undefined"!==typeof module&&(module.exports=a),process.on("uncaughtException",function(c){throw c;}),process.on("unhandledRejection",z),a.inspect=function(){return"[Emscripten Module object]"};
else if(aa)"undefined"!=typeof read&&(x=function(c){return read(c)}),y=function(c){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(c));c=read(c,"binary");assert("object"===typeof c);return c},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(t||u)u?w=self.location.href:document.currentScript&&(w=document.currentScript.src),w=0!==w.indexOf("blob:")?w.substr(0,
w.lastIndexOf("/")+1):"",x=function(c){var d=new XMLHttpRequest;d.open("GET",c,!1);d.send(null);return d.responseText},u&&(y=function(c){var d=new XMLHttpRequest;d.open("GET",c,!1);d.responseType="arraybuffer";d.send(null);return new Uint8Array(d.response)});else throw Error("environment detection error");a.print||console.log.bind(console);var A=a.printErr||console.warn.bind(console);for(r in b)b.hasOwnProperty(r)&&(a[r]=b[r]);b=null;
Object.getOwnPropertyDescriptor(a,"arguments")||Object.defineProperty(a,"arguments",{configurable:!0,get:function(){z("Module.arguments has been replaced with plain arguments_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});Object.getOwnPropertyDescriptor(a,"thisProgram")||Object.defineProperty(a,"thisProgram",{configurable:!0,get:function(){z("Module.thisProgram has been replaced with plain thisProgram (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
Object.getOwnPropertyDescriptor(a,"quit")||Object.defineProperty(a,"quit",{configurable:!0,get:function(){z("Module.quit has been replaced with plain quit_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});assert("undefined"===typeof a.memoryInitializerPrefixURL,"Module.memoryInitializerPrefixURL option was removed, use Module.locateFile instead");assert("undefined"===typeof a.pthreadMainPrefixURL,"Module.pthreadMainPrefixURL option was removed, use Module.locateFile instead");
assert("undefined"===typeof a.cdInitializerPrefixURL,"Module.cdInitializerPrefixURL option was removed, use Module.locateFile instead");assert("undefined"===typeof a.filePackagePrefixURL,"Module.filePackagePrefixURL option was removed, use Module.locateFile instead");assert("undefined"===typeof a.read,"Module.read option was removed (modify read_ in JS)");assert("undefined"===typeof a.readAsync,"Module.readAsync option was removed (modify readAsync in JS)");
assert("undefined"===typeof a.readBinary,"Module.readBinary option was removed (modify readBinary in JS)");assert("undefined"===typeof a.setWindowTitle,"Module.setWindowTitle option was removed (modify setWindowTitle in JS)");assert("undefined"===typeof a.TOTAL_MEMORY,"Module.TOTAL_MEMORY has been renamed Module.INITIAL_MEMORY");Object.getOwnPropertyDescriptor(a,"read")||Object.defineProperty(a,"read",{configurable:!0,get:function(){z("Module.read has been replaced with plain read_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
Object.getOwnPropertyDescriptor(a,"readAsync")||Object.defineProperty(a,"readAsync",{configurable:!0,get:function(){z("Module.readAsync has been replaced with plain readAsync (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});Object.getOwnPropertyDescriptor(a,"readBinary")||Object.defineProperty(a,"readBinary",{configurable:!0,get:function(){z("Module.readBinary has been replaced with plain readBinary (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
Object.getOwnPropertyDescriptor(a,"setWindowTitle")||Object.defineProperty(a,"setWindowTitle",{configurable:!0,get:function(){z("Module.setWindowTitle has been replaced with plain setWindowTitle (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});function ea(c){B||(B={});B[c]||(B[c]=1,A(c))}var B,C;a.wasmBinary&&(C=a.wasmBinary);
Object.getOwnPropertyDescriptor(a,"wasmBinary")||Object.defineProperty(a,"wasmBinary",{configurable:!0,get:function(){z("Module.wasmBinary has been replaced with plain wasmBinary (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});var noExitRuntime;a.noExitRuntime&&(noExitRuntime=a.noExitRuntime);Object.getOwnPropertyDescriptor(a,"noExitRuntime")||Object.defineProperty(a,"noExitRuntime",{configurable:!0,get:function(){z("Module.noExitRuntime has been replaced with plain noExitRuntime (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
"object"!==typeof WebAssembly&&z("no native wasm support detected");var D,fa=new WebAssembly.Table({initial:26,maximum:26,element:"anyfunc"}),ha=!1;function assert(c,d){c||z("Assertion failed: "+d)}function ia(c){var d=a["_"+c];assert(d,"Cannot call unknown function "+c+", make sure it is exported");return d}
function ja(c,d,e,f){var g={string:function(m){var n=0;if(null!==m&&void 0!==m&&0!==m){var q=(m.length<<2)+1;n=ka(q);la(m,n,q)}return n},array:function(m){var n=ka(m.length);assert(0<=m.length,"writeArrayToMemory array must have a length (should be an array or typed array)");E.set(m,n);return n}},h=ia(c),k=[];c=0;assert("array"!==d,'Return type should not be "array".');if(f)for(var l=0;l<f.length;l++){var p=g[e[l]];p?(0===c&&(c=ma()),k[l]=p(f[l])):k[l]=f[l]}e=h.apply(null,k);e=function(m){return"string"===
d?m?na(m,void 0):"":"boolean"===d?!!m:m}(e);0!==c&&oa(c);return e}var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function na(c,d){var e=F,f=c+d;for(d=c;e[d]&&!(d>=f);)++d;if(16<d-c&&e.subarray&&pa)return pa.decode(e.subarray(c,d));for(f="";c<d;){var g=e[c++];if(g&128){var h=e[c++]&63;if(192==(g&224))f+=String.fromCharCode((g&31)<<6|h);else{var k=e[c++]&63;224==(g&240)?g=(g&15)<<12|h<<6|k:(240!=(g&248)&&ea("Invalid UTF-8 leading byte 0x"+g.toString(16)+" encountered when deserializing a UTF-8 string on the asm.js/wasm heap to a JS string!"),g=(g&7)<<18|h<<12|k<<6|e[c++]&63);65536>g?f+=String.fromCharCode(g):
(g-=65536,f+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else f+=String.fromCharCode(g)}return f}
function la(c,d,e){assert("number"==typeof e,"stringToUTF8(str, outPtr, maxBytesToWrite) is missing the third parameter that specifies the length of the output buffer!");var f=F;if(0<e){e=d+e-1;for(var g=0;g<c.length;++g){var h=c.charCodeAt(g);if(55296<=h&&57343>=h){var k=c.charCodeAt(++g);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(d>=e)break;f[d++]=h}else{if(2047>=h){if(d+1>=e)break;f[d++]=192|h>>6}else{if(65535>=h){if(d+2>=e)break;f[d++]=224|h>>12}else{if(d+3>=e)break;2097152<=h&&ea("Invalid Unicode code point 0x"+
h.toString(16)+" encountered when serializing a JS string to an UTF-8 string on the asm.js/wasm heap! (Valid unicode code points should be in range 0-0x1FFFFF).");f[d++]=240|h>>18;f[d++]=128|h>>12&63}f[d++]=128|h>>6&63}f[d++]=128|h&63}}f[d]=0}}var qa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function sa(c,d){assert(0==c%2,"Pointer passed to UTF16ToString must be aligned to two bytes!");var e=c>>1;for(var f=e+d/2;!(e>=f)&&G[e];)++e;e<<=1;if(32<e-c&&qa)return qa.decode(F.subarray(c,e));e=0;for(f="";;){var g=H[c+2*e>>1];if(0==g||e==d/2)return f;++e;f+=String.fromCharCode(g)}}
function ta(c,d,e){assert(0==d%2,"Pointer passed to stringToUTF16 must be aligned to two bytes!");assert("number"==typeof e,"stringToUTF16(str, outPtr, maxBytesToWrite) is missing the third parameter that specifies the length of the output buffer!");void 0===e&&(e=2147483647);if(2>e)return 0;e-=2;var f=d;e=e<2*c.length?e/2:c.length;for(var g=0;g<e;++g)H[d>>1]=c.charCodeAt(g),d+=2;H[d>>1]=0;return d-f}function ua(c){return 2*c.length}
function va(c,d){assert(0==c%4,"Pointer passed to UTF32ToString must be aligned to four bytes!");for(var e=0,f="";!(e>=d/4);){var g=I[c+4*e>>2];if(0==g)break;++e;65536<=g?(g-=65536,f+=String.fromCharCode(55296|g>>10,56320|g&1023)):f+=String.fromCharCode(g)}return f}
function wa(c,d,e){assert(0==d%4,"Pointer passed to stringToUTF32 must be aligned to four bytes!");assert("number"==typeof e,"stringToUTF32(str, outPtr, maxBytesToWrite) is missing the third parameter that specifies the length of the output buffer!");void 0===e&&(e=2147483647);if(4>e)return 0;var f=d;e=f+e-4;for(var g=0;g<c.length;++g){var h=c.charCodeAt(g);if(55296<=h&&57343>=h){var k=c.charCodeAt(++g);h=65536+((h&1023)<<10)|k&1023}I[d>>2]=h;d+=4;if(d+4>e)break}I[d>>2]=0;return d-f}
function xa(c){for(var d=0,e=0;e<c.length;++e){var f=c.charCodeAt(e);55296<=f&&57343>=f&&++e;d+=4}return d}var J,E,F,H,G,I,L,ya,za;function Aa(c){J=c;a.HEAP8=E=new Int8Array(c);a.HEAP16=H=new Int16Array(c);a.HEAP32=I=new Int32Array(c);a.HEAPU8=F=new Uint8Array(c);a.HEAPU16=G=new Uint16Array(c);a.HEAPU32=L=new Uint32Array(c);a.HEAPF32=ya=new Float32Array(c);a.HEAPF64=za=new Float64Array(c)}assert(!0,"stack must start aligned");assert(!0,"heap must start aligned");
a.TOTAL_STACK&&assert(5242880===a.TOTAL_STACK,"the stack size can no longer be determined at runtime");var M=a.INITIAL_MEMORY||16777216;Object.getOwnPropertyDescriptor(a,"INITIAL_MEMORY")||Object.defineProperty(a,"INITIAL_MEMORY",{configurable:!0,get:function(){z("Module.INITIAL_MEMORY has been replaced with plain INITIAL_INITIAL_MEMORY (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
assert(5242880<=M,"INITIAL_MEMORY should be larger than TOTAL_STACK, was "+M+"! (TOTAL_STACK=5242880)");assert("undefined"!==typeof Int32Array&&"undefined"!==typeof Float64Array&&void 0!==Int32Array.prototype.subarray&&void 0!==Int32Array.prototype.set,"JS engine does not provide full typed array support");a.wasmMemory?D=a.wasmMemory:D=new WebAssembly.Memory({initial:M/65536,maximum:32768});D&&(J=D.buffer);M=J.byteLength;assert(0===M%65536);assert(!0);Aa(J);I[1264]=5247952;
function Ba(){assert(!0);L[1269]=34821223;L[1270]=2310721022;I[0]=1668509029}function N(){var c=L[1269],d=L[1270];34821223==c&&2310721022==d||z("Stack overflow! Stack cookie has been overwritten, expected hex dwords 0x89BACDFE and 0x2135467, but received 0x"+d.toString(16)+" "+c.toString(16));1668509029!==I[0]&&z("Runtime error: The application has corrupted its heap memory area (address zero)!")}var Ca=new Int16Array(1),Da=new Int8Array(Ca.buffer);Ca[0]=25459;
if(115!==Da[0]||99!==Da[1])throw"Runtime error: expected the system to be little-endian!";var Ea=[],Fa=[],Ga=[],Ha=[],Ia=!1;function Ja(){var c=a.preRun.shift();Ea.unshift(c)}assert(Math.imul,"This browser does not support Math.imul(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.fround,"This browser does not support Math.fround(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.clz32,"This browser does not support Math.clz32(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");
assert(Math.trunc,"This browser does not support Math.trunc(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");var O=0,P=null,Q=null,R={};
function Ka(){O++;a.monitorRunDependencies&&a.monitorRunDependencies(O);assert(!R["wasm-instantiate"]);R["wasm-instantiate"]=1;null===P&&"undefined"!==typeof setInterval&&(P=setInterval(function(){if(ha)clearInterval(P),P=null;else{var c=!1,d;for(d in R)c||(c=!0,A("still waiting on run dependencies:")),A("dependency: "+d);c&&A("(end of list)")}},1E4))}a.preloadedImages={};a.preloadedAudios={};
function z(c){if(a.onAbort)a.onAbort(c);A(c);ha=!0;c="abort("+c+") at ";a:{var d=Error();if(!d.stack){try{throw Error();}catch(e){d=e}if(!d.stack){d="(no stack trace available)";break a}}d=d.stack.toString()}a.extraStackTrace&&(d+="\n"+a.extraStackTrace());d=La(d);throw new WebAssembly.RuntimeError(c+d);}
function Ma(){z("Filesystem support (FS) was not included. The problem is that you are using files from JS, but files were not used from C/C++, so filesystem support was not auto-included. You can force-include filesystem support with  -s FORCE_FILESYSTEM=1")}a.FS_createDataFile=function(){Ma()};a.FS_createPreloadedFile=function(){Ma()};function Na(c){var d=S;return String.prototype.startsWith?d.startsWith(c):0===d.indexOf(c)}function Oa(){return Na("data:application/octet-stream;base64,")}
function T(c){return function(){var d=a.asm;assert(Ia,"native function `"+c+"` called before runtime initialization");assert(!0,"native function `"+c+"` called after runtime exit (use NO_EXIT_RUNTIME to keep it alive after main() exits)");d[c]||assert(d[c],"exported native function `"+c+"` not found");return d[c].apply(null,arguments)}}var S="fastled.wasm";if(!Oa()){var Pa=S;S=a.locateFile?a.locateFile(Pa,w):w+Pa}
function Qa(){try{if(C)return new Uint8Array(C);if(y)return y(S);throw"both async and sync fetching of the wasm failed";}catch(c){z(c)}}function Ra(){return C||!t&&!u||"function"!==typeof fetch||Na("file://")?Promise.resolve().then(Qa):fetch(S,{credentials:"same-origin"}).then(function(c){if(!c.ok)throw"failed to load wasm binary file at '"+S+"'";return c.arrayBuffer()}).catch(function(){return Qa()})}Fa.push({c:function(){Sa()}});
function Ta(c){for(;0<c.length;){var d=c.shift();if("function"==typeof d)d(a);else{var e=d.c;"number"===typeof e?void 0===d.b?fa.get(e)():fa.get(e)(d.b):e(void 0===d.b?null:d.b)}}}function La(c){return c.replace(/\b_Z[\w\d_]+/g,function(d){ea("warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling");return d===d?d:d+" ["+d+"]"})}function Ua(c){switch(c){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+c);}}
var Va=void 0;function U(c){for(var d="";F[c];)d+=Va[F[c++]];return d}var Wa={},Xa={},Ya={};function Za(c,d){if(void 0===c)c="_unknown";else{c=c.replace(/[^a-zA-Z0-9_]/g,"$");var e=c.charCodeAt(0);c=48<=e&&57>=e?"_"+c:c}return(new Function("body","return function "+c+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(d)}
function $a(c){var d=Error,e=Za(c,function(f){this.name=c;this.message=f;f=Error(f).stack;void 0!==f&&(this.stack=this.toString()+"\n"+f.replace(/^Error(:[^\n]*)?\n/,""))});e.prototype=Object.create(d.prototype);e.prototype.constructor=e;e.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return e}var ab=void 0;function V(c){throw new ab(c);}
function W(c,d,e){e=e||{};if(!("argPackAdvance"in d))throw new TypeError("registerType registeredInstance requires argPackAdvance");var f=d.name;c||V('type "'+f+'" must have a positive integer typeid pointer');if(Xa.hasOwnProperty(c)){if(e.f)return;V("Cannot register type '"+f+"' twice")}Xa[c]=d;delete Ya[c];Wa.hasOwnProperty(c)&&(d=Wa[c],delete Wa[c],d.forEach(function(g){g()}))}var bb=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function cb(c){switch(c){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var d=bb.length?bb.pop():X.length;X[d]={g:1,value:c};return d}}function db(c){return this.fromWireType(L[c>>2])}function eb(c){if(null===c)return"null";var d=typeof c;return"object"===d||"array"===d||"function"===d?c.toString():""+c}
function fb(c,d){switch(d){case 2:return function(e){return this.fromWireType(ya[e>>2])};case 3:return function(e){return this.fromWireType(za[e>>3])};default:throw new TypeError("Unknown float type: "+c);}}
function gb(c,d,e){switch(d){case 0:return e?function(f){return E[f]}:function(f){return F[f]};case 1:return e?function(f){return H[f>>1]}:function(f){return G[f>>1]};case 2:return e?function(f){return I[f>>2]}:function(f){return L[f>>2]};default:throw new TypeError("Unknown integer type: "+c);}}var Y;v?Y=function(){var c=process.hrtime();return 1E3*c[0]+c[1]/1E6}:"undefined"!==typeof dateNow?Y=dateNow:Y=function(){return performance.now()};for(var hb=Array(256),ib=0;256>ib;++ib)hb[ib]=String.fromCharCode(ib);
Va=hb;ab=a.BindingError=$a("BindingError");a.InternalError=$a("InternalError");a.count_emval_handles=function(){for(var c=0,d=5;d<X.length;++d)void 0!==X[d]&&++c;return c};a.get_first_emval=function(){for(var c=5;c<X.length;++c)if(void 0!==X[c])return X[c];return null};
var kb={_embind_register_bool:function(c,d,e,f,g){var h=Ua(e);d=U(d);W(c,{name:d,fromWireType:function(k){return!!k},toWireType:function(k,l){return l?f:g},argPackAdvance:8,readValueFromPointer:function(k){if(1===e)var l=E;else if(2===e)l=H;else if(4===e)l=I;else throw new TypeError("Unknown boolean type size: "+d);return this.fromWireType(l[k>>h])},a:null})},_embind_register_emval:function(c,d){d=U(d);W(c,{name:d,fromWireType:function(e){var f=X[e].value;4<e&&0===--X[e].g&&(X[e]=void 0,bb.push(e));
return f},toWireType:function(e,f){return cb(f)},argPackAdvance:8,readValueFromPointer:db,a:null})},_embind_register_float:function(c,d,e){e=Ua(e);d=U(d);W(c,{name:d,fromWireType:function(f){return f},toWireType:function(f,g){if("number"!==typeof g&&"boolean"!==typeof g)throw new TypeError('Cannot convert "'+eb(g)+'" to '+this.name);return g},argPackAdvance:8,readValueFromPointer:fb(d,e),a:null})},_embind_register_integer:function(c,d,e,f,g){function h(m){return m}d=U(d);-1===g&&(g=4294967295);var k=
Ua(e);if(0===f){var l=32-8*e;h=function(m){return m<<l>>>l}}var p=-1!=d.indexOf("unsigned");W(c,{name:d,fromWireType:h,toWireType:function(m,n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+eb(n)+'" to '+this.name);if(n<f||n>g)throw new TypeError('Passing a number "'+eb(n)+'" from JS side to C/C++ side to an argument of type "'+d+'", which is outside the valid range ['+f+", "+g+"]!");return p?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:gb(d,k,0!==f),a:null})},
_embind_register_memory_view:function(c,d,e){function f(h){h>>=2;var k=L;return new g(J,k[h+1],k[h])}var g=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][d];e=U(e);W(c,{name:e,fromWireType:f,argPackAdvance:8,readValueFromPointer:f},{f:!0})},_embind_register_std_string:function(c,d){d=U(d);var e="std::string"===d;W(c,{name:d,fromWireType:function(f){var g=L[f>>2];if(e)for(var h=f+4,k=0;k<=g;++k){var l=f+4+k;if(k==g||0==F[l]){h=h?na(h,l-h):"";if(void 0===
p)var p=h;else p+=String.fromCharCode(0),p+=h;h=l+1}}else{p=Array(g);for(k=0;k<g;++k)p[k]=String.fromCharCode(F[f+4+k]);p=p.join("")}Z(f);return p},toWireType:function(f,g){g instanceof ArrayBuffer&&(g=new Uint8Array(g));var h="string"===typeof g;h||g instanceof Uint8Array||g instanceof Uint8ClampedArray||g instanceof Int8Array||V("Cannot pass non-string to std::string");var k=(e&&h?function(){for(var m=0,n=0;n<g.length;++n){var q=g.charCodeAt(n);55296<=q&&57343>=q&&(q=65536+((q&1023)<<10)|g.charCodeAt(++n)&
1023);127>=q?++m:m=2047>=q?m+2:65535>=q?m+3:m+4}return m}:function(){return g.length})(),l=jb(4+k+1);L[l>>2]=k;if(e&&h)la(g,l+4,k+1);else if(h)for(h=0;h<k;++h){var p=g.charCodeAt(h);255<p&&(Z(l),V("String has UTF-16 code units that do not fit in 8 bits"));F[l+4+h]=p}else for(h=0;h<k;++h)F[l+4+h]=g[h];null!==f&&f.push(Z,l);return l},argPackAdvance:8,readValueFromPointer:db,a:function(f){Z(f)}})},_embind_register_std_wstring:function(c,d,e){e=U(e);if(2===d){var f=sa;var g=ta;var h=ua;var k=function(){return G};
var l=1}else 4===d&&(f=va,g=wa,h=xa,k=function(){return L},l=2);W(c,{name:e,fromWireType:function(p){for(var m=L[p>>2],n=k(),q,K=p+4,ca=0;ca<=m;++ca){var ra=p+4+ca*d;if(ca==m||0==n[ra>>l])K=f(K,ra-K),void 0===q?q=K:(q+=String.fromCharCode(0),q+=K),K=ra+d}Z(p);return q},toWireType:function(p,m){"string"!==typeof m&&V("Cannot pass non-string to C++ string type "+e);var n=h(m),q=jb(4+n+d);L[q>>2]=n>>l;g(m,q+4,n+d);null!==p&&p.push(Z,q);return q},argPackAdvance:8,readValueFromPointer:db,a:function(p){Z(p)}})},
_embind_register_void:function(c,d){d=U(d);W(c,{h:!0,name:d,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},abort:function(){z()},emscripten_get_sbrk_ptr:function(){return 5056},emscripten_memcpy_big:function(c,d,e){F.copyWithin(c,d,d+e)},emscripten_resize_heap:function(c){c>>>=0;var d=F.length;assert(c>d);if(2147483648<c)return A("Cannot enlarge memory, asked to go up to "+c+" bytes, but the limit is 2147483648 bytes!"),!1;for(var e=1;4>=e;e*=2){var f=d*(1+.2/e);f=Math.min(f,
c+100663296);f=Math.max(16777216,c,f);0<f%65536&&(f+=65536-f%65536);f=Math.min(2147483648,f);var g=Y();a:{var h=f;try{D.grow(h-J.byteLength+65535>>>16);Aa(D.buffer);var k=1;break a}catch(l){console.error("emscripten_realloc_buffer: Attempted to grow heap from "+J.byteLength+" bytes to "+h+" bytes, but got error: "+l)}k=void 0}h=Y();console.log("Heap resize call from "+d+" to "+f+" took "+(h-g)+" msecs. Success: "+!!k);if(k)return!0}A("Failed to grow the heap from "+d+" bytes to "+f+" bytes, not enough memory!");
return!1},gettimeofday:function(c){var d=Date.now();I[c>>2]=d/1E3|0;I[c+4>>2]=d%1E3*1E3|0;return 0},memory:D,table:fa};
(function(){function c(h){a.asm=h.exports;O--;a.monitorRunDependencies&&a.monitorRunDependencies(O);assert(R["wasm-instantiate"]);delete R["wasm-instantiate"];0==O&&(null!==P&&(clearInterval(P),P=null),Q&&(h=Q,Q=null,h()))}function d(h){assert(a===g,"the Module object should not be replaced during async compilation - perhaps the order of HTML elements is wrong?");g=null;c(h.instance)}function e(h){return Ra().then(function(k){return WebAssembly.instantiate(k,f)}).then(h,function(k){A("failed to asynchronously prepare wasm: "+
k);z(k)})}var f={env:kb,wasi_snapshot_preview1:kb};Ka();var g=a;if(a.instantiateWasm)try{return a.instantiateWasm(f,c)}catch(h){return A("Module.instantiateWasm callback failed with error: "+h),!1}(function(){if(C||"function"!==typeof WebAssembly.instantiateStreaming||Oa()||Na("file://")||"function"!==typeof fetch)return e(d);fetch(S,{credentials:"same-origin"}).then(function(h){return WebAssembly.instantiateStreaming(h,f).then(d,function(k){A("wasm streaming compile failed: "+k);A("falling back to ArrayBuffer instantiation");
return e(d)})})})();return{}})();var Sa=a.___wasm_call_ctors=T("__wasm_call_ctors");a._demo_reel100=T("demo_reel100");a._demo_pride=T("demo_pride");a._demo_twinklefox=T("demo_twinklefox");a._demo_fire2012=T("demo_fire2012");a._demo_pacifica=T("demo_pacifica");a.___getTypeName=T("__getTypeName");a.___embind_register_native_and_builtin_types=T("__embind_register_native_and_builtin_types");a.___errno_location=T("__errno_location");var jb=a._malloc=T("malloc");a._fflush=T("fflush");
var ma=a.stackSave=T("stackSave"),oa=a.stackRestore=T("stackRestore"),ka=a.stackAlloc=T("stackAlloc"),Z=a._free=T("free");a.__growWasmMemory=T("__growWasmMemory");Object.getOwnPropertyDescriptor(a,"intArrayFromString")||(a.intArrayFromString=function(){z("'intArrayFromString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"intArrayToString")||(a.intArrayToString=function(){z("'intArrayToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
a.ccall=ja;a.cwrap=function(c,d,e,f){return function(){return ja(c,d,e,arguments,f)}};Object.getOwnPropertyDescriptor(a,"setValue")||(a.setValue=function(){z("'setValue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getValue")||(a.getValue=function(){z("'getValue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"allocate")||(a.allocate=function(){z("'allocate' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getMemory")||(a.getMemory=function(){z("'getMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"UTF8ArrayToString")||(a.UTF8ArrayToString=function(){z("'UTF8ArrayToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"UTF8ToString")||(a.UTF8ToString=function(){z("'UTF8ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToUTF8Array")||(a.stringToUTF8Array=function(){z("'stringToUTF8Array' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToUTF8")||(a.stringToUTF8=function(){z("'stringToUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"lengthBytesUTF8")||(a.lengthBytesUTF8=function(){z("'lengthBytesUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stackTrace")||(a.stackTrace=function(){z("'stackTrace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addOnPreRun")||(a.addOnPreRun=function(){z("'addOnPreRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"addOnInit")||(a.addOnInit=function(){z("'addOnInit' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addOnPreMain")||(a.addOnPreMain=function(){z("'addOnPreMain' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addOnExit")||(a.addOnExit=function(){z("'addOnExit' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"addOnPostRun")||(a.addOnPostRun=function(){z("'addOnPostRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeStringToMemory")||(a.writeStringToMemory=function(){z("'writeStringToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeArrayToMemory")||(a.writeArrayToMemory=function(){z("'writeArrayToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"writeAsciiToMemory")||(a.writeAsciiToMemory=function(){z("'writeAsciiToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addRunDependency")||(a.addRunDependency=function(){z("'addRunDependency' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"removeRunDependency")||(a.removeRunDependency=function(){z("'removeRunDependency' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"FS_createFolder")||(a.FS_createFolder=function(){z("'FS_createFolder' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"FS_createPath")||(a.FS_createPath=function(){z("'FS_createPath' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"FS_createDataFile")||(a.FS_createDataFile=function(){z("'FS_createDataFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"FS_createPreloadedFile")||(a.FS_createPreloadedFile=function(){z("'FS_createPreloadedFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"FS_createLazyFile")||(a.FS_createLazyFile=function(){z("'FS_createLazyFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"FS_createLink")||(a.FS_createLink=function(){z("'FS_createLink' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"FS_createDevice")||(a.FS_createDevice=function(){z("'FS_createDevice' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"FS_unlink")||(a.FS_unlink=function(){z("'FS_unlink' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"dynamicAlloc")||(a.dynamicAlloc=function(){z("'dynamicAlloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"loadDynamicLibrary")||(a.loadDynamicLibrary=function(){z("'loadDynamicLibrary' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"loadWebAssemblyModule")||(a.loadWebAssemblyModule=function(){z("'loadWebAssemblyModule' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getLEB")||(a.getLEB=function(){z("'getLEB' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getFunctionTables")||(a.getFunctionTables=function(){z("'getFunctionTables' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"alignFunctionTables")||(a.alignFunctionTables=function(){z("'alignFunctionTables' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registerFunctions")||(a.registerFunctions=function(){z("'registerFunctions' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"addFunction")||(a.addFunction=function(){z("'addFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"removeFunction")||(a.removeFunction=function(){z("'removeFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getFuncWrapper")||(a.getFuncWrapper=function(){z("'getFuncWrapper' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"prettyPrint")||(a.prettyPrint=function(){z("'prettyPrint' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"makeBigInt")||(a.makeBigInt=function(){z("'makeBigInt' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"dynCall")||(a.dynCall=function(){z("'dynCall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getCompilerSetting")||(a.getCompilerSetting=function(){z("'getCompilerSetting' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"print")||(a.print=function(){z("'print' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"printErr")||(a.printErr=function(){z("'printErr' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getTempRet0")||(a.getTempRet0=function(){z("'getTempRet0' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"setTempRet0")||(a.setTempRet0=function(){z("'setTempRet0' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"callMain")||(a.callMain=function(){z("'callMain' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"abort")||(a.abort=function(){z("'abort' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToNewUTF8")||(a.stringToNewUTF8=function(){z("'stringToNewUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emscripten_realloc_buffer")||(a.emscripten_realloc_buffer=function(){z("'emscripten_realloc_buffer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"ENV")||(a.ENV=function(){z("'ENV' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ERRNO_CODES")||(a.ERRNO_CODES=function(){z("'ERRNO_CODES' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ERRNO_MESSAGES")||(a.ERRNO_MESSAGES=function(){z("'ERRNO_MESSAGES' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"setErrNo")||(a.setErrNo=function(){z("'setErrNo' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"DNS")||(a.DNS=function(){z("'DNS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GAI_ERRNO_MESSAGES")||(a.GAI_ERRNO_MESSAGES=function(){z("'GAI_ERRNO_MESSAGES' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"Protocols")||(a.Protocols=function(){z("'Protocols' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"Sockets")||(a.Sockets=function(){z("'Sockets' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"traverseStack")||(a.traverseStack=function(){z("'traverseStack' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"UNWIND_CACHE")||(a.UNWIND_CACHE=function(){z("'UNWIND_CACHE' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"withBuiltinMalloc")||(a.withBuiltinMalloc=function(){z("'withBuiltinMalloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"readAsmConstArgsArray")||(a.readAsmConstArgsArray=function(){z("'readAsmConstArgsArray' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"readAsmConstArgs")||(a.readAsmConstArgs=function(){z("'readAsmConstArgs' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"mainThreadEM_ASM")||(a.mainThreadEM_ASM=function(){z("'mainThreadEM_ASM' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"jstoi_q")||(a.jstoi_q=function(){z("'jstoi_q' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"jstoi_s")||(a.jstoi_s=function(){z("'jstoi_s' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getExecutableName")||(a.getExecutableName=function(){z("'getExecutableName' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"listenOnce")||(a.listenOnce=function(){z("'listenOnce' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"autoResumeAudioContext")||(a.autoResumeAudioContext=function(){z("'autoResumeAudioContext' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"dynCallLegacy")||(a.dynCallLegacy=function(){z("'dynCallLegacy' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getDynCaller")||(a.getDynCaller=function(){z("'getDynCaller' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"dynCall")||(a.dynCall=function(){z("'dynCall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"callRuntimeCallbacks")||(a.callRuntimeCallbacks=function(){z("'callRuntimeCallbacks' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"abortStackOverflow")||(a.abortStackOverflow=function(){z("'abortStackOverflow' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"reallyNegative")||(a.reallyNegative=function(){z("'reallyNegative' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"unSign")||(a.unSign=function(){z("'unSign' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"reSign")||(a.reSign=function(){z("'reSign' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"formatString")||(a.formatString=function(){z("'formatString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"PATH")||(a.PATH=function(){z("'PATH' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"PATH_FS")||(a.PATH_FS=function(){z("'PATH_FS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"SYSCALLS")||(a.SYSCALLS=function(){z("'SYSCALLS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"syscallMmap2")||(a.syscallMmap2=function(){z("'syscallMmap2' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"syscallMunmap")||(a.syscallMunmap=function(){z("'syscallMunmap' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"flush_NO_FILESYSTEM")||(a.flush_NO_FILESYSTEM=function(){z("'flush_NO_FILESYSTEM' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"JSEvents")||(a.JSEvents=function(){z("'JSEvents' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"specialHTMLTargets")||(a.specialHTMLTargets=function(){z("'specialHTMLTargets' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"maybeCStringToJsString")||(a.maybeCStringToJsString=function(){z("'maybeCStringToJsString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"findEventTarget")||(a.findEventTarget=function(){z("'findEventTarget' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"findCanvasEventTarget")||(a.findCanvasEventTarget=function(){z("'findCanvasEventTarget' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"polyfillSetImmediate")||(a.polyfillSetImmediate=function(){z("'polyfillSetImmediate' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"demangle")||(a.demangle=function(){z("'demangle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"demangleAll")||(a.demangleAll=function(){z("'demangleAll' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"jsStackTrace")||(a.jsStackTrace=function(){z("'jsStackTrace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stackTrace")||(a.stackTrace=function(){z("'stackTrace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getEnvStrings")||(a.getEnvStrings=function(){z("'getEnvStrings' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"checkWasiClock")||(a.checkWasiClock=function(){z("'checkWasiClock' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeI53ToI64")||(a.writeI53ToI64=function(){z("'writeI53ToI64' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeI53ToI64Clamped")||(a.writeI53ToI64Clamped=function(){z("'writeI53ToI64Clamped' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"writeI53ToI64Signaling")||(a.writeI53ToI64Signaling=function(){z("'writeI53ToI64Signaling' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeI53ToU64Clamped")||(a.writeI53ToU64Clamped=function(){z("'writeI53ToU64Clamped' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeI53ToU64Signaling")||(a.writeI53ToU64Signaling=function(){z("'writeI53ToU64Signaling' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"readI53FromI64")||(a.readI53FromI64=function(){z("'readI53FromI64' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"readI53FromU64")||(a.readI53FromU64=function(){z("'readI53FromU64' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"convertI32PairToI53")||(a.convertI32PairToI53=function(){z("'convertI32PairToI53' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"convertU32PairToI53")||(a.convertU32PairToI53=function(){z("'convertU32PairToI53' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"exceptionLast")||(a.exceptionLast=function(){z("'exceptionLast' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"exceptionCaught")||(a.exceptionCaught=function(){z("'exceptionCaught' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"exceptionThrowBuf")||(a.exceptionThrowBuf=function(){z("'exceptionThrowBuf' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ExceptionInfoAttrs")||(a.ExceptionInfoAttrs=function(){z("'ExceptionInfoAttrs' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ExceptionInfo")||(a.ExceptionInfo=function(){z("'ExceptionInfo' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"CatchInfo")||(a.CatchInfo=function(){z("'CatchInfo' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"exception_addRef")||(a.exception_addRef=function(){z("'exception_addRef' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"exception_decRef")||(a.exception_decRef=function(){z("'exception_decRef' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"Browser")||(a.Browser=function(){z("'Browser' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"funcWrappers")||(a.funcWrappers=function(){z("'funcWrappers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getFuncWrapper")||(a.getFuncWrapper=function(){z("'getFuncWrapper' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"setMainLoop")||(a.setMainLoop=function(){z("'setMainLoop' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"FS")||(a.FS=function(){z("'FS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"MEMFS")||(a.MEMFS=function(){z("'MEMFS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"TTY")||(a.TTY=function(){z("'TTY' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"PIPEFS")||(a.PIPEFS=function(){z("'PIPEFS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"SOCKFS")||(a.SOCKFS=function(){z("'SOCKFS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"tempFixedLengthArray")||(a.tempFixedLengthArray=function(){z("'tempFixedLengthArray' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"miniTempWebGLFloatBuffers")||(a.miniTempWebGLFloatBuffers=function(){z("'miniTempWebGLFloatBuffers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"heapObjectForWebGLType")||(a.heapObjectForWebGLType=function(){z("'heapObjectForWebGLType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"heapAccessShiftForWebGLHeap")||(a.heapAccessShiftForWebGLHeap=function(){z("'heapAccessShiftForWebGLHeap' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GL")||(a.GL=function(){z("'GL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGet")||(a.emscriptenWebGLGet=function(){z("'emscriptenWebGLGet' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"computeUnpackAlignedImageSize")||(a.computeUnpackAlignedImageSize=function(){z("'computeUnpackAlignedImageSize' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGetTexPixelData")||(a.emscriptenWebGLGetTexPixelData=function(){z("'emscriptenWebGLGetTexPixelData' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGetUniform")||(a.emscriptenWebGLGetUniform=function(){z("'emscriptenWebGLGetUniform' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGetVertexAttrib")||(a.emscriptenWebGLGetVertexAttrib=function(){z("'emscriptenWebGLGetVertexAttrib' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"writeGLArray")||(a.writeGLArray=function(){z("'writeGLArray' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"AL")||(a.AL=function(){z("'AL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"SDL_unicode")||(a.SDL_unicode=function(){z("'SDL_unicode' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"SDL_ttfContext")||(a.SDL_ttfContext=function(){z("'SDL_ttfContext' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"SDL_audio")||(a.SDL_audio=function(){z("'SDL_audio' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"SDL")||(a.SDL=function(){z("'SDL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"SDL_gfx")||(a.SDL_gfx=function(){z("'SDL_gfx' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GLUT")||(a.GLUT=function(){z("'GLUT' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"EGL")||(a.EGL=function(){z("'EGL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"GLFW_Window")||(a.GLFW_Window=function(){z("'GLFW_Window' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GLFW")||(a.GLFW=function(){z("'GLFW' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GLEW")||(a.GLEW=function(){z("'GLEW' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"IDBStore")||(a.IDBStore=function(){z("'IDBStore' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"runAndAbortIfError")||(a.runAndAbortIfError=function(){z("'runAndAbortIfError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emval_handle_array")||(a.emval_handle_array=function(){z("'emval_handle_array' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"emval_free_list")||(a.emval_free_list=function(){z("'emval_free_list' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emval_symbols")||(a.emval_symbols=function(){z("'emval_symbols' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"init_emval")||(a.init_emval=function(){z("'init_emval' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"count_emval_handles")||(a.count_emval_handles=function(){z("'count_emval_handles' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"get_first_emval")||(a.get_first_emval=function(){z("'get_first_emval' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getStringOrSymbol")||(a.getStringOrSymbol=function(){z("'getStringOrSymbol' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"requireHandle")||(a.requireHandle=function(){z("'requireHandle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emval_newers")||(a.emval_newers=function(){z("'emval_newers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"craftEmvalAllocator")||(a.craftEmvalAllocator=function(){z("'craftEmvalAllocator' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"emval_get_global")||(a.emval_get_global=function(){z("'emval_get_global' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emval_methodCallers")||(a.emval_methodCallers=function(){z("'emval_methodCallers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"InternalError")||(a.InternalError=function(){z("'InternalError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"BindingError")||(a.BindingError=function(){z("'BindingError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"UnboundTypeError")||(a.UnboundTypeError=function(){z("'UnboundTypeError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"PureVirtualError")||(a.PureVirtualError=function(){z("'PureVirtualError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"init_embind")||(a.init_embind=function(){z("'init_embind' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"throwInternalError")||(a.throwInternalError=function(){z("'throwInternalError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"throwBindingError")||(a.throwBindingError=function(){z("'throwBindingError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"throwUnboundTypeError")||(a.throwUnboundTypeError=function(){z("'throwUnboundTypeError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ensureOverloadTable")||(a.ensureOverloadTable=function(){z("'ensureOverloadTable' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"exposePublicSymbol")||(a.exposePublicSymbol=function(){z("'exposePublicSymbol' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"replacePublicSymbol")||(a.replacePublicSymbol=function(){z("'replacePublicSymbol' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"extendError")||(a.extendError=function(){z("'extendError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"createNamedFunction")||(a.createNamedFunction=function(){z("'createNamedFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"registeredInstances")||(a.registeredInstances=function(){z("'registeredInstances' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getBasestPointer")||(a.getBasestPointer=function(){z("'getBasestPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registerInheritedInstance")||(a.registerInheritedInstance=function(){z("'registerInheritedInstance' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"unregisterInheritedInstance")||(a.unregisterInheritedInstance=function(){z("'unregisterInheritedInstance' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getInheritedInstance")||(a.getInheritedInstance=function(){z("'getInheritedInstance' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getInheritedInstanceCount")||(a.getInheritedInstanceCount=function(){z("'getInheritedInstanceCount' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getLiveInheritedInstances")||(a.getLiveInheritedInstances=function(){z("'getLiveInheritedInstances' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registeredTypes")||(a.registeredTypes=function(){z("'registeredTypes' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"awaitingDependencies")||(a.awaitingDependencies=function(){z("'awaitingDependencies' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"typeDependencies")||(a.typeDependencies=function(){z("'typeDependencies' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registeredPointers")||(a.registeredPointers=function(){z("'registeredPointers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"registerType")||(a.registerType=function(){z("'registerType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"whenDependentTypesAreResolved")||(a.whenDependentTypesAreResolved=function(){z("'whenDependentTypesAreResolved' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"embind_charCodes")||(a.embind_charCodes=function(){z("'embind_charCodes' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"embind_init_charCodes")||(a.embind_init_charCodes=function(){z("'embind_init_charCodes' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"readLatin1String")||(a.readLatin1String=function(){z("'readLatin1String' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getTypeName")||(a.getTypeName=function(){z("'getTypeName' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"heap32VectorToArray")||(a.heap32VectorToArray=function(){z("'heap32VectorToArray' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"requireRegisteredType")||(a.requireRegisteredType=function(){z("'requireRegisteredType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getShiftFromSize")||(a.getShiftFromSize=function(){z("'getShiftFromSize' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"integerReadValueFromPointer")||(a.integerReadValueFromPointer=function(){z("'integerReadValueFromPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"enumReadValueFromPointer")||(a.enumReadValueFromPointer=function(){z("'enumReadValueFromPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"floatReadValueFromPointer")||(a.floatReadValueFromPointer=function(){z("'floatReadValueFromPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"simpleReadValueFromPointer")||(a.simpleReadValueFromPointer=function(){z("'simpleReadValueFromPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"runDestructors")||(a.runDestructors=function(){z("'runDestructors' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"new_")||(a.new_=function(){z("'new_' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"craftInvokerFunction")||(a.craftInvokerFunction=function(){z("'craftInvokerFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"embind__requireFunction")||(a.embind__requireFunction=function(){z("'embind__requireFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"tupleRegistrations")||(a.tupleRegistrations=function(){z("'tupleRegistrations' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"structRegistrations")||(a.structRegistrations=function(){z("'structRegistrations' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"genericPointerToWireType")||(a.genericPointerToWireType=function(){z("'genericPointerToWireType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"constNoSmartPtrRawPointerToWireType")||(a.constNoSmartPtrRawPointerToWireType=function(){z("'constNoSmartPtrRawPointerToWireType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"nonConstNoSmartPtrRawPointerToWireType")||(a.nonConstNoSmartPtrRawPointerToWireType=function(){z("'nonConstNoSmartPtrRawPointerToWireType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"init_RegisteredPointer")||(a.init_RegisteredPointer=function(){z("'init_RegisteredPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"RegisteredPointer")||(a.RegisteredPointer=function(){z("'RegisteredPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"RegisteredPointer_getPointee")||(a.RegisteredPointer_getPointee=function(){z("'RegisteredPointer_getPointee' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"RegisteredPointer_destructor")||(a.RegisteredPointer_destructor=function(){z("'RegisteredPointer_destructor' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"RegisteredPointer_deleteObject")||(a.RegisteredPointer_deleteObject=function(){z("'RegisteredPointer_deleteObject' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"RegisteredPointer_fromWireType")||(a.RegisteredPointer_fromWireType=function(){z("'RegisteredPointer_fromWireType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"runDestructor")||(a.runDestructor=function(){z("'runDestructor' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"releaseClassHandle")||(a.releaseClassHandle=function(){z("'releaseClassHandle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"finalizationGroup")||(a.finalizationGroup=function(){z("'finalizationGroup' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"detachFinalizer_deps")||(a.detachFinalizer_deps=function(){z("'detachFinalizer_deps' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"detachFinalizer")||(a.detachFinalizer=function(){z("'detachFinalizer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"attachFinalizer")||(a.attachFinalizer=function(){z("'attachFinalizer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"makeClassHandle")||(a.makeClassHandle=function(){z("'makeClassHandle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"init_ClassHandle")||(a.init_ClassHandle=function(){z("'init_ClassHandle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"ClassHandle")||(a.ClassHandle=function(){z("'ClassHandle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ClassHandle_isAliasOf")||(a.ClassHandle_isAliasOf=function(){z("'ClassHandle_isAliasOf' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"throwInstanceAlreadyDeleted")||(a.throwInstanceAlreadyDeleted=function(){z("'throwInstanceAlreadyDeleted' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"ClassHandle_clone")||(a.ClassHandle_clone=function(){z("'ClassHandle_clone' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ClassHandle_delete")||(a.ClassHandle_delete=function(){z("'ClassHandle_delete' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"deletionQueue")||(a.deletionQueue=function(){z("'deletionQueue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"ClassHandle_isDeleted")||(a.ClassHandle_isDeleted=function(){z("'ClassHandle_isDeleted' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ClassHandle_deleteLater")||(a.ClassHandle_deleteLater=function(){z("'ClassHandle_deleteLater' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"flushPendingDeletes")||(a.flushPendingDeletes=function(){z("'flushPendingDeletes' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"delayFunction")||(a.delayFunction=function(){z("'delayFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"setDelayFunction")||(a.setDelayFunction=function(){z("'setDelayFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"RegisteredClass")||(a.RegisteredClass=function(){z("'RegisteredClass' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"shallowCopyInternalPointer")||(a.shallowCopyInternalPointer=function(){z("'shallowCopyInternalPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"downcastPointer")||(a.downcastPointer=function(){z("'downcastPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"upcastPointer")||(a.upcastPointer=function(){z("'upcastPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"validateThis")||(a.validateThis=function(){z("'validateThis' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"char_0")||(a.char_0=function(){z("'char_0' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"char_9")||(a.char_9=function(){z("'char_9' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"makeLegalFunctionName")||(a.makeLegalFunctionName=function(){z("'makeLegalFunctionName' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"warnOnce")||(a.warnOnce=function(){z("'warnOnce' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stackSave")||(a.stackSave=function(){z("'stackSave' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"stackRestore")||(a.stackRestore=function(){z("'stackRestore' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stackAlloc")||(a.stackAlloc=function(){z("'stackAlloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"AsciiToString")||(a.AsciiToString=function(){z("'AsciiToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"stringToAscii")||(a.stringToAscii=function(){z("'stringToAscii' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"UTF16ToString")||(a.UTF16ToString=function(){z("'UTF16ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToUTF16")||(a.stringToUTF16=function(){z("'stringToUTF16' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"lengthBytesUTF16")||(a.lengthBytesUTF16=function(){z("'lengthBytesUTF16' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"UTF32ToString")||(a.UTF32ToString=function(){z("'UTF32ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToUTF32")||(a.stringToUTF32=function(){z("'stringToUTF32' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"lengthBytesUTF32")||(a.lengthBytesUTF32=function(){z("'lengthBytesUTF32' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"allocateUTF8")||(a.allocateUTF8=function(){z("'allocateUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"allocateUTF8OnStack")||(a.allocateUTF8OnStack=function(){z("'allocateUTF8OnStack' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
a.writeStackCookie=Ba;a.checkStackCookie=N;Object.getOwnPropertyDescriptor(a,"ALLOC_NORMAL")||Object.defineProperty(a,"ALLOC_NORMAL",{configurable:!0,get:function(){z("'ALLOC_NORMAL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});Object.getOwnPropertyDescriptor(a,"ALLOC_STACK")||Object.defineProperty(a,"ALLOC_STACK",{configurable:!0,get:function(){z("'ALLOC_STACK' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});
Object.getOwnPropertyDescriptor(a,"ALLOC_DYNAMIC")||Object.defineProperty(a,"ALLOC_DYNAMIC",{configurable:!0,get:function(){z("'ALLOC_DYNAMIC' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});Object.getOwnPropertyDescriptor(a,"ALLOC_NONE")||Object.defineProperty(a,"ALLOC_NONE",{configurable:!0,get:function(){z("'ALLOC_NONE' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});var lb;Q=function mb(){lb||nb();lb||(Q=mb)};
function nb(){function c(){if(!lb&&(lb=!0,a.calledRun=!0,!ha)){N();assert(!Ia);Ia=!0;Ta(Fa);N();Ta(Ga);if(a.onRuntimeInitialized)a.onRuntimeInitialized();assert(!a._main,'compiled without a main, but one is present. if you added it from JS, use Module["onRuntimeInitialized"]');N();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var d=a.postRun.shift();Ha.unshift(d)}Ta(Ha)}}if(!(0<O)){Ba();if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)Ja();
Ta(Ea);0<O||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);c()},1)):c(),N())}}a.run=nb;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();noExitRuntime=!0;nb();
