name: build

on:
  push:
    branches:
      - prepare_release

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: compile to WASM
        uses: docker://emscripten/emsdk:2.0.2
        with:
          args: sh -c "cd /github/workspace && make"
      - name: upload to github pages
        uses: peaceiris/actions-gh-pages@8a36f3edfc5d1cbae6b09e6f5a7d7b19e5b7a73b
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
          allow_empty_commit: true
